
"""create initial tables

Revision ID: 35acfde348b0
Revises: 
Create Date: 2026-03-02 17:17:26.766570
"""

from alembic import op
import sqlalchemy as sa

revision = '35acfde348b0'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
